# Local development dependencies
name: housing-challenge
channels:
  - conda-forge
dependencies:
  - python=3.13

  # Required
  - anyio==4.11.0
  - fastapi[standard]==0.121.3
  - gunicorn==23.0.0
  - h11==0.16.0
  - joblib==1.5.2
  - libopenblas==0.3.30
  - libuv==1.51.0
  - numpy==2.3.5
  - orjson==3.11.4
  - pandas==2.3.3
  - pydantic==2.12.4
  - scikit-learn==1.7.2
  - scipy==1.16.3
  - starlette==0.50.0
  - uvicorn==0.38.0
  - uvicorn-worker==0.4.0
  - uvloop==0.22.1

  # Code checks
  - black==25.1.0
  - pylint==4.0.3
  - isort==7.0.0
  - mypy==1.18.2

  # Test dependencies
  - pytest==9.0.1
