name: housing-challenge-train
channels:
  - conda-forge
dependencies:
  - python=3.13

  - joblib==1.5.2
  - libopenblas==0.3.30
  - numpy==2.3.5
  - pandas==2.3.3
  - scikit-learn==1.7.2
  - scipy==1.16.3
